#!/usr/bin/env bash
# Regenerates src/boring_gen.rs from boring/breakout.br, via the project's
# ../boring.toml (project mode: `boring build --emit-rust` with no file
# argument) rather than passing breakout.br as a direct file path -- this is
# what makes boring.toml's [external_types] section apply (see that file's
# comment for why it's declared despite being redundant with boring's own
# built-in whitelist right now).
#
# Requires a `boring` CLI built from the `boring` repo's `main` branch. Point
# BORING_BIN at that binary, e.g.:
#
#   git -C ../../boring worktree add ../../.boring-main-worktree main
#   (cd ../../.boring-main-worktree && cargo build --release)
#   export BORING_BIN=../../.boring-main-worktree/target/release/boring
#   ./regen.sh
set -euo pipefail

BORING_BIN="${BORING_BIN:-boring}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$PROJECT_ROOT/src/boring_gen.rs"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

(cd "$PROJECT_ROOT" && "$BORING_BIN" build --emit-rust) > "$tmp"

{
  echo "// AUTO-GENERATED by boring/regen.sh from boring/breakout.br — do not hand-edit."
  echo "// Regenerate with: (cd boring && ./regen.sh)"
  # unused_parens: the transpiler emits a fully-parenthesized AST verbatim
  # (e.g. `(dist_sq > (ball_radius * ball_radius))`), which is correct but
  # noisy — not something to hand-fix in a generated file.
  #
  # dead_code specifically also covers `fn main` below being unused from
  # the [lib] target's perspective (this same file is both [lib]'s and
  # [[bin]]'s crate root — see ../Cargo.toml/../README.md) — the [lib]
  # compilation never calls it, only the [[bin]] one does.
  echo "#![allow(dead_code, non_snake_case, unused_imports, unused_parens, unused_mut, unused_variables)]"
  echo
  # breakout.br's trailing `def main(): run_game()` is kept this time —
  # unlike bevy-boring's sim.br (which strips this, since that project's
  # boring_gen.rs is only ever a [lib] submodule with its own separate
  # hand-written src/main.rs), this file IS the real crate entry point
  # too: no separate main.rs exists at all.
  cat "$tmp"
} > "$OUT"

echo "wrote $OUT"
