// AUTO-GENERATED by boring/regen.sh from boring/breakout.br — do not hand-edit.
// Regenerate with: (cd boring && ./regen.sh)
#![allow(dead_code, non_snake_case, unused_imports, unused_parens, unused_mut, unused_variables)]

// Generated by boring build
use std::collections::{HashMap, HashSet};
use std::hash::Hash;
use std::rc::{Rc, Weak};
use std::sync::Arc;
use std::sync::{Mutex, RwLock};
use std::f64::consts::{PI, E, TAU};
use std::time::Duration;

trait BoringArrayIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Vec<Self::Item>;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone> BoringArrayIndex for Vec<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Vec<T> {
        let mut v = self.clone();
        if let Some(i) = i { if i < v.len() { v.remove(i); } }
        v
    }
    fn get_at(&self, i: Option<usize>) -> T {
        self[i.expect("get_at called with no index (empty collection or exhausted cursor)")].clone()
    }
}
trait BoringDictIndex<K: Clone + Eq + std::hash::Hash, V: Clone> {
    fn first_index(&self) -> Option<K>;
    fn next_index(&self, k: K) -> Option<K>;
    fn remove_at(&self, k: Option<K>) -> Self where Self: Sized;
}
impl<K: Clone + Eq + std::hash::Hash, V: Clone> BoringDictIndex<K, V> for HashMap<K, V> {
    fn first_index(&self) -> Option<K> { self.keys().next().cloned() }
    fn next_index(&self, k: K) -> Option<K> {
        let keys: Vec<_> = self.keys().collect();
        let pos = keys.iter().position(|kk| *kk == &k);
        pos.and_then(|p| keys.get(p + 1)).map(|kk| (*kk).clone())
    }
    fn remove_at(&self, k: Option<K>) -> Self { let mut m = self.clone(); if let Some(k) = k { m.remove(&k); } m }
}
trait BoringSetIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Self where Self: Sized;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone + Eq + std::hash::Hash> BoringSetIndex for HashSet<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Self {
        let elem = i.and_then(|i| self.iter().nth(i).cloned());
        let mut s = self.clone();
        if let Some(e) = elem { s.remove(&e); }
        s
    }
    fn get_at(&self, i: Option<usize>) -> T {
        let i = i.expect("get_at called with no index (empty collection or exhausted cursor)");
        self.iter().nth(i).cloned().expect("get_at index out of range")
    }
}

// BoringFmt — displays Vec<T: Display> as [a, b, c] (no debug quotes on strings).
struct BoringFmt<'a, T: std::fmt::Display>(pub &'a [T]);
impl<'a, T: std::fmt::Display> std::fmt::Display for BoringFmt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.0.iter().enumerate() {
            if i > 0 { write!(f, ", ")?; }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

// BoringVal — bridge trait that gives BoringError::Other both Display and Any (downcast).
// Every user-defined error enum automatically satisfies the blanket impl below.
trait BoringVal: std::fmt::Display + std::any::Any + Send + Sync {
    fn as_any(&self) -> &dyn std::any::Any;
}
impl<T: std::fmt::Display + std::any::Any + Send + Sync + 'static> BoringVal for T {
    fn as_any(&self) -> &dyn std::any::Any { self }
}
impl std::fmt::Debug for dyn BoringVal + Send + Sync {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "BoringVal({})", self)
    }
}

// BoringError — typed exception wrapper so `catch String:` / `catch Int:` / `catch MyError:` can dispatch.
// `Other(TypeId, error)` identifies the thrown type uniquely across modules via std::any::TypeId::of::<T>(),
// which requires no instance — fully collision-free even when two modules define identically-named types.
//
// `Scalar(ScalarKind, u128)` is the fixed-width numeric family's own path —
// int8..int128, uint8..uint128, and float32 — kept OUT of `Other` on purpose
// (docs/float-width-types.md §7): the compiler already knows, statically,
// that a thrown value here is exactly one of eleven small Copy kinds, so
// paying for a heap allocation + `dyn Any` downcast the way `Other` does for
// arbitrary user enums/structs would be pure overhead. The raw bits are
// reinterpreted per `kind` in `Display` below and at each `catch` arm —
// sign/zero-extended into the shared `u128` slot on the way in, truncated (or
// bit-reinterpreted, for float32) back to the exact original type on the way
// out; this round-trips exactly, it never touches `Other`'s TypeId machinery
// at all. `float`/`float64` deliberately stay on their own pre-existing
// `BoringError::Float(f64)` fast path instead of joining `Scalar` — unlike
// the other eleven kinds, they already had a dedicated, no-allocation
// representation before this family existed, and giving them a second,
// parallel one here would only create two disjoint representations for the
// same type with no single `catch` spelling reliably catching both (a literal
// float throw and a `float64`-typed variable throw would land in different
// variants). `Other` still exists, narrowed to what only it can do: genuine
// user-defined enums/structs the compiler can't enumerate in advance.
#[derive(Debug, Clone, Copy, PartialEq)]
enum ScalarKind { Int8, Int16, Int32, Int64, Int128, Uint8, Uint16, Uint32, Uint64, Uint128, Float32 }
impl BoringError {
    fn scalar_i8(v: i8) -> Self { BoringError::Scalar(ScalarKind::Int8, v as i128 as u128) }
    fn scalar_i16(v: i16) -> Self { BoringError::Scalar(ScalarKind::Int16, v as i128 as u128) }
    fn scalar_i32(v: i32) -> Self { BoringError::Scalar(ScalarKind::Int32, v as i128 as u128) }
    fn scalar_i64(v: i64) -> Self { BoringError::Scalar(ScalarKind::Int64, v as i128 as u128) }
    fn scalar_i128(v: i128) -> Self { BoringError::Scalar(ScalarKind::Int128, v as u128) }
    fn scalar_u8(v: u8) -> Self { BoringError::Scalar(ScalarKind::Uint8, v as u128) }
    fn scalar_u16(v: u16) -> Self { BoringError::Scalar(ScalarKind::Uint16, v as u128) }
    fn scalar_u32(v: u32) -> Self { BoringError::Scalar(ScalarKind::Uint32, v as u128) }
    fn scalar_u64(v: u64) -> Self { BoringError::Scalar(ScalarKind::Uint64, v as u128) }
    fn scalar_u128(v: u128) -> Self { BoringError::Scalar(ScalarKind::Uint128, v) }
    fn scalar_f32(v: f32) -> Self { BoringError::Scalar(ScalarKind::Float32, v.to_bits() as u128) }
}
#[derive(Debug)]
enum BoringError {
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(&'static str),
    String(Arc<str>),
    Scalar(ScalarKind, u128),
    Other(std::any::TypeId, std::boxed::Box<dyn BoringVal + Send + Sync>),
}
impl std::fmt::Display for BoringError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            BoringError::Int(n)         => write!(f, "{}", n),
            BoringError::Float(n)       => write!(f, "{}", n),
            BoringError::Bool(b)        => write!(f, "{}", b),
            BoringError::Str(s)         => write!(f, "{}", s),
            BoringError::String(s)      => write!(f, "{}", s),
            BoringError::Scalar(k, bits) => match k {
                ScalarKind::Int8    => write!(f, "{}", *bits as i128 as i8),
                ScalarKind::Int16   => write!(f, "{}", *bits as i128 as i16),
                ScalarKind::Int32   => write!(f, "{}", *bits as i128 as i32),
                ScalarKind::Int64   => write!(f, "{}", *bits as i128 as i64),
                ScalarKind::Int128  => write!(f, "{}", *bits as i128),
                ScalarKind::Uint8   => write!(f, "{}", *bits as u8),
                ScalarKind::Uint16  => write!(f, "{}", *bits as u16),
                ScalarKind::Uint32  => write!(f, "{}", *bits as u32),
                ScalarKind::Uint64  => write!(f, "{}", *bits as u64),
                ScalarKind::Uint128 => write!(f, "{}", *bits),
                ScalarKind::Float32 => write!(f, "{}", f32::from_bits(*bits as u32)),
            },
            BoringError::Other(_, e)    => write!(f, "{}", e),
        }
    }
}
impl std::error::Error for BoringError {}

// Boring standard error enum — always available without import.
// Use `throw Error.Expired` / `catch Error:` / `match err: Error.Expired: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum Error {
    Expired,
    Cancelled,
    NotFound,
    InvalidInput,
    OutOfBounds,
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::Expired      => write!(f, "timeout expired"),
            Error::Cancelled    => write!(f, "task cancelled"),
            Error::NotFound     => write!(f, "not found"),
            Error::InvalidInput => write!(f, "invalid input"),
            Error::OutOfBounds  => write!(f, "index out of bounds"),
        }
    }
}
impl std::error::Error for Error {}

// Boring GPU error enum — thrown by kernel dispatch on a device-side
// failure. Always available without import. Currently wired up on the
// wgpu target only (its host codegen shares this same general pipeline);
// cuda/rocm/metal report GPU failures as plain string-message errors
// instead of this typed enum -- see `docs/gpu-module.md`'s error-handling
// notes for why (their host transpilers don't share this prelude).
// Use `catch GpuError.OutOfMemory:` / `match err: GpuError.Timeout: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum GpuError {
    LaunchError,
    OutOfMemory,
    IllegalAccess,
    StackOverflow,
    Timeout,
    DeviceLost,
}
impl std::fmt::Display for GpuError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            GpuError::LaunchError   => write!(f, "GPU kernel launch failed"),
            GpuError::OutOfMemory   => write!(f, "GPU out of memory"),
            GpuError::IllegalAccess => write!(f, "GPU illegal memory access"),
            GpuError::StackOverflow => write!(f, "GPU stack overflow"),
            GpuError::Timeout       => write!(f, "GPU operation timed out"),
            GpuError::DeviceLost    => write!(f, "GPU device lost"),
        }
    }
}
impl std::error::Error for GpuError {}

use bevy::prelude::*;

pub const LEFT_WALL: f32 = (-450.0);

pub const RIGHT_WALL: f32 = 450.0;

pub const BOTTOM_WALL: f32 = (-300.0);

pub const TOP_WALL: f32 = 300.0;

const WALL_THICKNESS: f32 = 10.0;

const PADDLE_PADDING: f32 = 10.0;

const PADDLE_SPEED: f32 = 500.0;

pub const BALL_DIAMETER: f32 = 30.0;

const GAP_BETWEEN_PADDLE_AND_FLOOR: f32 = 60.0;

const BALL_SPEED: f32 = 400.0;

const GAP_BETWEEN_PADDLE_AND_BRICKS: f32 = 270.0;

const GAP_BETWEEN_BRICKS: f32 = 5.0;

const GAP_BETWEEN_BRICKS_AND_CEILING: f32 = 20.0;

const GAP_BETWEEN_BRICKS_AND_SIDES: f32 = 20.0;

const PADDLE_SIZE: Vec2 = Vec2::new(120.0, 20.0);

const BALL_STARTING_POSITION: Vec3 = Vec3::new(0.0, (-50.0), 1.0);

const INITIAL_BALL_DIRECTION: Vec2 = Vec2::new(0.5, (-0.5));

const BRICK_SIZE: Vec2 = Vec2::new(100.0, 30.0);

const PADDLE_COLOR: Color = Color::srgb(0.3, 0.3, 0.7);

const BALL_COLOR: Color = Color::srgb(1.0, 0.5, 0.5);

const BRICK_COLOR: Color = Color::srgb(0.5, 0.5, 1.0);

const WALL_COLOR: Color = Color::srgb(0.8, 0.8, 0.8);

const BACKGROUND_COLOR: Color = Color::srgb(0.9, 0.9, 0.9);

#[derive(Debug, Clone, PartialEq, Component)]
pub struct Paddle {
}

impl std::fmt::Display for Paddle {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Paddle {
}

#[derive(Debug, Clone, PartialEq, Component)]
pub struct Ball {
}

impl std::fmt::Display for Ball {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Ball {
}

#[derive(Debug, Clone, PartialEq, Component)]
pub struct Brick {
}

impl std::fmt::Display for Brick {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Brick {
}

#[derive(Debug, Clone, PartialEq, Component, Default)]
pub struct Collider {
}

impl std::fmt::Display for Collider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Collider {
}

#[derive(Debug, Clone, PartialEq, Component)]
#[require(Sprite, Transform, Collider)]
pub struct Wall {
}

impl std::fmt::Display for Wall {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Wall {
}

#[derive(Debug, Clone, PartialEq, Component)]
pub struct ScoreboardUi {
}

impl std::fmt::Display for ScoreboardUi {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl ScoreboardUi {
}

#[derive(Debug, Clone, PartialEq, Event)]
pub struct BallCollided {
}

impl std::fmt::Display for BallCollided {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl BallCollided {
}

#[derive(Debug, Clone, PartialEq, Component)]
pub struct Velocity {
    pub x: f32,
    pub y: f32,
}

impl std::fmt::Display for Velocity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Velocity {
}

#[derive(Debug, Clone, PartialEq, Resource)]
pub struct Score {
    pub count: /* var */ isize,
}

impl std::fmt::Display for Score {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Score {
    pub fn new() -> Self {
        Score {
            count: 0,
        }
    }

    pub fn increment(&mut self) -> () {
        self.count += 1;
    }

}

#[derive(Resource, Deref, Debug)]
pub struct CollisionSound {
    pub handle: Handle<AudioSource>,
}

impl std::fmt::Display for CollisionSound {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl CollisionSound {
}

#[derive(Debug, Clone, PartialEq)]
pub struct Point {
    pub x: f32,
    pub y: f32,
}

impl std::fmt::Display for Point {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Point {
}

#[derive(Debug, Clone, PartialEq)]
pub struct BrickLayout {
    pub n_columns: isize,
    pub n_rows: isize,
    pub offset_x: f32,
    pub offset_y: f32,
}

impl std::fmt::Display for BrickLayout {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl BrickLayout {
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WallLocation {
    Left,
    Right,
    Bottom,
    Top,
}

impl std::fmt::Display for WallLocation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl WallLocation {
    pub fn position(&self) -> Point {
        match self {
            WallLocation::Left => {
                Point { x: LEFT_WALL, y: 0.0 }
            }
            WallLocation::Right => {
                Point { x: RIGHT_WALL, y: 0.0 }
            }
            WallLocation::Bottom => {
                Point { x: 0.0, y: BOTTOM_WALL }
            }
            WallLocation::Top => {
                Point { x: 0.0, y: TOP_WALL }
            }
        }
    }

    pub fn size(&self) -> Point {
        let arena_height = (TOP_WALL - BOTTOM_WALL);
        let arena_width = (RIGHT_WALL - LEFT_WALL);
        assert!((arena_height > 0.0));
        assert!((arena_width > 0.0));
        match self {
            WallLocation::Left => {
                Point { x: WALL_THICKNESS, y: (arena_height + WALL_THICKNESS) }
            }
            WallLocation::Right => {
                Point { x: WALL_THICKNESS, y: (arena_height + WALL_THICKNESS) }
            }
            WallLocation::Bottom => {
                Point { x: (arena_width + WALL_THICKNESS), y: WALL_THICKNESS }
            }
            WallLocation::Top => {
                Point { x: (arena_width + WALL_THICKNESS), y: WALL_THICKNESS }
            }
        }
    }

}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Collision {
    Left,
    Right,
    Top,
    Bottom,
}

impl std::fmt::Display for Collision {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}


pub fn move_by_velocity(pos: &Point, v: &Velocity, dt: f32) -> Point {
    Point { x: (pos.x + (v.x * dt)), y: (pos.y + (v.y * dt)) }
}

pub fn clamp_paddle_x(current_x: f32, direction: f32, speed: f32, dt: f32, left_bound: f32, right_bound: f32) -> f32 {
    let new_x = (current_x + ((direction * speed) * dt));
    (new_x).clamp(left_bound, right_bound)
}

pub fn ball_collision(ball_center: &Point, ball_radius: f32, box_center: &Point, box_half_size: &Point) -> Option<Collision> {
    let closest_x = (ball_center.x).clamp((box_center.x - box_half_size.x), (box_center.x + box_half_size.x));
    let closest_y = (ball_center.y).clamp((box_center.y - box_half_size.y), (box_center.y + box_half_size.y));
    let offset_x = (ball_center.x - closest_x);
    let offset_y = (ball_center.y - closest_y);
    let dist_sq = ((offset_x * offset_x) + (offset_y * offset_y));
    if (dist_sq > (ball_radius * ball_radius)) {
        return None;
    }
    if ((offset_x as f32).abs() > (offset_y as f32).abs()) {
        if (offset_x < 0.0) {
            return Some(Collision::Left);
        } else {
            return Some(Collision::Right);
        }
    } else {
        if (offset_y > 0.0) {
            return Some(Collision::Top);
        } else {
            return Some(Collision::Bottom);
        }
    }
}

pub fn reflect_velocity(v: &Velocity, c: Collision) -> Velocity {
    let mut reflect_x = false;
    let mut reflect_y = false;
    match c {
        Collision::Left => {
            reflect_x = (v.x > 0.0);
        }
        Collision::Right => {
            reflect_x = (v.x < 0.0);
        }
        Collision::Top => {
            reflect_y = (v.y < 0.0);
        }
        Collision::Bottom => {
            reflect_y = (v.y > 0.0);
        }
    }
    let nx =     match reflect_x {
        true => {
            (-v.x)
        }
        false => {
            v.x
        }
    };
    let ny =     match reflect_y {
        true => {
            (-v.y)
        }
        false => {
            v.y
        }
    };
    Velocity { x: nx, y: ny }
}

pub fn brick_layout(total_width: f32, total_height: f32, brick_w: f32, brick_h: f32, gap: f32, left_wall: f32, right_wall: f32, bricks_bottom_y: f32) -> BrickLayout {
    assert!((total_width > 0.0));
    assert!((total_height > 0.0));
    let n_columns = (((total_width / (brick_w + gap)) as f32).floor() as isize);
    let n_rows = (((total_height / (brick_h + gap)) as f32).floor() as isize);
    let n_vertical_gaps = (n_columns - 1);
    let center_x = ((left_wall + right_wall) / 2.0);
    let left_edge = ((center_x - (((n_columns as f32) / 2.0) * brick_w)) - (((n_vertical_gaps as f32) / 2.0) * gap));
    let offset_x = (left_edge + (brick_w / 2.0));
    let offset_y = (bricks_bottom_y + (brick_h / 2.0));
    BrickLayout { n_columns: n_columns, n_rows: n_rows, offset_x: offset_x, offset_y: offset_y }
}

pub fn brick_position(layout: &BrickLayout, row: isize, column: isize, brick_w: f32, brick_h: f32, gap: f32) -> Point {
    Point { x: (layout.offset_x + ((column as f32) * (brick_w + gap))), y: (layout.offset_y + ((row as f32) * (brick_h + gap))) }
}

pub fn wall_bundle(location: WallLocation) -> (Wall, Sprite, Transform) {
    let pos = location.position();
    let size = location.size();
    (Wall {}, Sprite::from_color(WALL_COLOR, Vec2::ONE), Transform { translation: Vec3::new(pos.x, pos.y, 0.0), scale: Vec3::new(size.x, size.y, 1.0), ..Default::default() })
}

pub fn spawn_camera(mut commands: Commands) -> () {
    commands.spawn(Camera2d);
}

pub fn set_clear_color(mut commands: Commands) -> () {
    commands.insert_resource(ClearColor(BACKGROUND_COLOR));
}

pub fn load_collision_sound(mut commands: Commands, asset_server: Res<AssetServer>) -> () {
    let handle = asset_server.load("sounds/breakout_collision.ogg");
    commands.insert_resource(CollisionSound { handle: handle });
}

pub fn spawn_paddle(mut commands: Commands) -> () {
    let paddle_y = (BOTTOM_WALL + GAP_BETWEEN_PADDLE_AND_FLOOR);
    commands.spawn((Sprite::from_color(PADDLE_COLOR, Vec2::ONE), Transform { translation: Vec3::new(0.0, paddle_y, 0.0), scale: PADDLE_SIZE.extend(1.0), ..Default::default() }, Paddle {}, Collider {}));
}

pub fn spawn_ball(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>, mut materials: ResMut<Assets<ColorMaterial>>) -> () {
    let initial_velocity = (INITIAL_BALL_DIRECTION.normalize() * BALL_SPEED);
    commands.spawn((Mesh2d(meshes.add(Circle::default())), MeshMaterial2d(materials.add(BALL_COLOR)), Transform::from_translation(BALL_STARTING_POSITION).with_scale(Vec2::splat(BALL_DIAMETER).extend(1.0)), Ball {}, Velocity { x: initial_velocity.x, y: initial_velocity.y }));
}

pub fn spawn_walls(mut commands: Commands) -> () {
    commands.spawn(wall_bundle(WallLocation::Left.clone()));
    commands.spawn(wall_bundle(WallLocation::Right.clone()));
    commands.spawn(wall_bundle(WallLocation::Bottom.clone()));
    commands.spawn(wall_bundle(WallLocation::Top.clone()));
}

pub fn spawn_bricks(mut commands: Commands) -> () {
    let paddle_y = (BOTTOM_WALL + GAP_BETWEEN_PADDLE_AND_FLOOR);
    let total_width_of_bricks = ((RIGHT_WALL - LEFT_WALL) - (2.0 * GAP_BETWEEN_BRICKS_AND_SIDES));
    let bottom_edge_of_bricks = (paddle_y + GAP_BETWEEN_PADDLE_AND_BRICKS);
    let total_height_of_bricks = ((TOP_WALL - bottom_edge_of_bricks) - GAP_BETWEEN_BRICKS_AND_CEILING);
    let layout = brick_layout(total_width_of_bricks, total_height_of_bricks, BRICK_SIZE.x.clone(), BRICK_SIZE.y.clone(), GAP_BETWEEN_BRICKS, LEFT_WALL, RIGHT_WALL, bottom_edge_of_bricks);
    for row in (0..layout.n_rows) {
        for column in (0..layout.n_columns) {
            let pos = brick_position(&layout, row, column, BRICK_SIZE.x.clone(), BRICK_SIZE.y.clone(), GAP_BETWEEN_BRICKS);
            commands.spawn((Sprite { color: BRICK_COLOR, ..Default::default() }, Transform { translation: Vec3::new(pos.x, pos.y, 0.0), scale: Vec3::new(BRICK_SIZE.x, BRICK_SIZE.y, 1.0), ..Default::default() }, Brick {}, Collider {}));
        }
    }
}

pub fn apply_velocity(query: Query<(&mut Transform, &Velocity)>, time: Res<Time>) -> () {
    let dt = time.delta_secs();
    for (mut transform, velocity) in query.into_iter() {
        let next = move_by_velocity(&Point { x: transform.translation.x, y: transform.translation.y }, &velocity, dt);
        transform.translation.x = next.x;
        transform.translation.y = next.y;
    }
}

pub fn move_paddle(keyboard_input: Res<ButtonInput<KeyCode>>, mut paddle_transform: Single<&mut Transform, With<Paddle>>, time: Res<Time>) -> () {
    let mut direction = 0.0;
    if keyboard_input.pressed(KeyCode::ArrowLeft) {
        direction -= 1.0;
    }
    if keyboard_input.pressed(KeyCode::ArrowRight) {
        direction += 1.0;
    }
    let left_bound = (((LEFT_WALL + (WALL_THICKNESS / 2.0)) + (PADDLE_SIZE.x / 2.0)) + PADDLE_PADDING);
    let right_bound = (((RIGHT_WALL - (WALL_THICKNESS / 2.0)) - (PADDLE_SIZE.x / 2.0)) - PADDLE_PADDING);
    let new_x = clamp_paddle_x(paddle_transform.translation.x.clone(), direction, PADDLE_SPEED, time.delta_secs(), left_bound, right_bound);
    paddle_transform.translation.x = new_x.clone();
}

pub fn check_for_collisions(mut commands: Commands, mut score: ResMut<Score>, mut ball_query: Single<(&mut Velocity, &Transform), With<Ball>>, collider_query: Query<(Entity, &Transform, Option<&Brick>), With<Collider>>) -> () {
    let mut ball = ball_query.into_inner();
    for (entity, collider_transform, maybe_brick) in collider_query.into_iter() {
        let maybe_collision = ball_collision(&Point { x: ball.1.translation.x, y: ball.1.translation.y }, (BALL_DIAMETER / 2.0), &Point { x: collider_transform.translation.x, y: collider_transform.translation.y }, &Point { x: (collider_transform.scale.x / 2.0), y: (collider_transform.scale.y / 2.0) });
        if let Some(collision) = maybe_collision {
            commands.trigger(BallCollided {});
            if maybe_brick.is_some() {
                commands.entity(entity).despawn();
                score.increment();
            }
            let reflected = reflect_velocity(&Velocity { x: ball.0.x, y: ball.0.y }, collision.clone());
            ball.0.x = reflected.x;
            ball.0.y = reflected.y;
        }
    }
}

pub fn play_collision_sound(collided: On<BallCollided>, mut commands: Commands, sound: Res<CollisionSound>) -> () {
    commands.spawn(AudioPlayer::new(sound.clone()));
}

const SCOREBOARD_FONT_SIZE: FontSize = FontSize::Px(33.0);

const SCOREBOARD_TEXT_PADDING: Val = Val::Px(5.0);

const TEXT_COLOR: Color = Color::srgb(0.5, 0.5, 1.0);

const SCORE_COLOR: Color = Color::srgb(1.0, 0.5, 0.5);

pub fn spawn_scoreboard_ui(mut commands: Commands) -> () {
    let mut root = commands.spawn((Text::new("Score: "), TextFont { font_size: SCOREBOARD_FONT_SIZE, ..Default::default() }, TextColor(TEXT_COLOR), ScoreboardUi {}, Node { position_type: PositionType::Absolute, top: SCOREBOARD_TEXT_PADDING, left: SCOREBOARD_TEXT_PADDING, ..Default::default() }));
    root.with_children(|parent| drop(parent.spawn((TextSpan::default(), TextFont { font_size: SCOREBOARD_FONT_SIZE, ..Default::default() }, TextColor(SCORE_COLOR)))));
}

pub fn update_scoreboard(score: Res<Score>, score_root: Single<Entity, (With<ScoreboardUi>, With<Text>)>, mut writer: TextUiWriter) -> () {
    *writer.text(*score_root, 1) = Arc::<str>::from(format!("{}", score.count).as_str()).to_string();
}

pub fn build_app() -> App {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.insert_resource(Score { count: 0 });
    app.add_systems(Startup, (set_clear_color, spawn_camera, load_collision_sound, spawn_paddle, spawn_ball, spawn_walls, spawn_bricks, spawn_scoreboard_ui));
    app.add_systems(Update, (apply_velocity, move_paddle, check_for_collisions).chain());
    app.add_systems(Update, update_scoreboard);
    app.add_observer(play_collision_sound);
    app
}

pub fn run_game() -> () {
    build_app().run();
}

fn main() -> () {
    run_game();
}

